### ISSUE TITLE
advise to change the default color

### ISSUE THREAD

**Issue by shAdow-XJY** [Skylled/expansion_tile_card#32]
the default color is themeData.accentColor, which will be unused in beta version. 
In future releases, there may be errors during compilation and packaging, resulting in failure to compile.

```
Failed to build iOS app
Error (Xcode): ../.pub-cache/hosted/pub.dev/expansion_tile_card-2.0.0/lib/expansion_tile_card.dart:337:49: Error: The getter 'accentColor' isn't defined for the class 'ThemeData'.
```

**Comment by awaik** [comment]
Fixed with this PR https://github.com/Skylled/expansion_tile_card/pull/33

Temporary you can use in pubspec.yaml

```
dependency_overrides:
  expansion_tile_card:
    git:
      url: https://github.com/awaik/expansion_tile_card/
      ref: fix_theme_issue
```
